version: '3'

services:
  dubbo-provider:
    image: hub.harbor.com:8850/dubbo-spring-cloud-demo/dubbo-provider:0.0.1-SNAPSHOT
    command:
    - "--nacos.address=192.168.0.103"
    restart: always

  dubbo-consumer:
    image: hub.harbor.com:8850/dubbo-spring-cloud-demo/dubbo-consumer:0.0.1-SNAPSHOT
    links:
    - dubbo-provider
    command:
    - "--nacos.address=192.168.0.103"
    ports:
    - 8001:8001
    restart: always